### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: '2024_01_17_15_55_17/video_temp/2024_01_17_15.56.20/Benjamin##0_enhanced.mp4' -> '2024_01_17_15_55_17/video/0.mp4'

### ISSUE THREAD

**Issue by NoTfReEzY** [AkshitIreddy/AI-Powered-Video-Tutorial-Generator#4]
i am facing the error of file not found of the result generated by sadtalker as i have tried generating sadtalker output manually it is generating properly but with this project it is acting abnormally am not able to identify that is it error with my installation or something else ....
 just faced this errors along with it
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
Traceback (most recent call last):
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\SadTalker\inference.py", line 154, in <module>
    main(args)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\SadTalker\inference.py", line 38, in main
    preprocess_model = CropAndExtract(sadtalker_paths, device)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\SadTalker\src\utils\preprocess.py", line 56, in __init__
    checkpoint = torch.load(sadtalker_path['path_of_net_recon_model'], map_location=torch.device(device))
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\SadTalker\venv\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\SadTalker\venv\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\SadTalker\venv\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints\\epoch_20.pth'
INFO:     127.0.0.1:56034 - "POST /videoCreate HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '2024_01_17_15_55_17/video_temp/2024_01_17_15.56.20/Benjamin##0_enhanced.mp4' -> '2024_01_17_15_55_17/video/0.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\.venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\main.py", line 30, in create_insights    
    path = video_main(message, level, age, creative, humour, characterName)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\functions\video_main_function.py", line 23, in video_main
    create_video_from_audio(timestamp, character_name)
  File "C:\Users\Desktop\project\AI-Powered-Video-Tutorial-Generator\backend\functions\create_video_from_audio_function.py", line 29, in create_video_from_audio
    shutil.move(video_path, video_output_path)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '2024_01_17_15_55_17/video_temp/2024_01_17_15.56.20/Benjamin##0_enhanced.mp4'

**Comment by AkshitIreddy** [comment]
If it is not able to find the video then it probably means the video was not generated by a sadtalker which can happen if the inputs provided to it were missing/invalid, this can happen if either function responsible for generating the video dialogue or audio fails , or there is a chance that it is having some incompatibility errors because I haven't updated it in months.

**Comment by NoTfReEzY** [comment]
ohh so will it work properly by degrading sadtalker version right? can you help me with version you used previously

**Comment by AkshitIreddy** [comment]
> ohh so will it work properly by degrading sadtalker version right? can you help me with version you used previously
> 

I don't remember the version number but my other project llm NPCs uses sadtalker, you can download that repo and copy the sadtalker files from there and paste it at the location mentioned here.

**Comment by NoTfReEzY** [comment]
ok thanks for your time
